// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2m35vs3iLJbPtLS1L88mcc7mbLM5PKSs',
    appId: '1:555974802803:web:3f3253e410833a05edd906',
    messagingSenderId: '555974802803',
    projectId: 'vitraeview-77e68',
    authDomain: 'vitraeview-77e68.firebaseapp.com',
    storageBucket: 'vitraeview-77e68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4iyjwlqsRZG9T-TN1Dd3_B9aytpNr-s',
    appId: '1:555974802803:android:870c04d89e09f410edd906',
    messagingSenderId: '555974802803',
    projectId: 'vitraeview-77e68',
    storageBucket: 'vitraeview-77e68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOopu_sccYPrnGHw178JMsPQvF0R67nS0',
    appId: '1:555974802803:ios:97543952d1e09b16edd906',
    messagingSenderId: '555974802803',
    projectId: 'vitraeview-77e68',
    storageBucket: 'vitraeview-77e68.firebasestorage.app',
    iosBundleId: 'com.example.vitraeView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOopu_sccYPrnGHw178JMsPQvF0R67nS0',
    appId: '1:555974802803:ios:97543952d1e09b16edd906',
    messagingSenderId: '555974802803',
    projectId: 'vitraeview-77e68',
    storageBucket: 'vitraeview-77e68.firebasestorage.app',
    iosBundleId: 'com.example.vitraeView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2m35vs3iLJbPtLS1L88mcc7mbLM5PKSs',
    appId: '1:555974802803:web:e7205e8e44086569edd906',
    messagingSenderId: '555974802803',
    projectId: 'vitraeview-77e68',
    authDomain: 'vitraeview-77e68.firebaseapp.com',
    storageBucket: 'vitraeview-77e68.firebasestorage.app',
  );
}
